### PR TITLE
Include software_parameters

### PR DESCRIPTION
**Pull request by jarsi**
If I am not mistaken, software_parameters should be imported in order for the replacement in the jobfile to work.

### CODE REVIEW

**Comment by jasperalbers** [comment]
Hmm, I'm curious why my tests after the introduction of `software parameters` worked then. Looking at the code, the `bench` step should at least make use of `$buildermod` from this set. @ackurth @Kaveh01 what do you think?

**Comment by Kaveh01** [comment]
> Hmm, I'm curious why my tests after the introduction of `software parameters` worked then. Looking at the code, the `bench` step should at least make use of `$buildermod` from this set. @ackurth @Kaveh01 what do you think?

@jasperalbers  I guess you used an old config file that had no software_parameters and everything was in the machine_parameters. I looked at my files and I only had software_parameters in the template and not the actual config file and that was the reason I did not see the issue.

**Comment by jasperalbers** [comment]
@Kaveh01 I agree, sounds like a reasonable explanation.

**Review by jasperalbers — APPROVED** [review]
Changes look good!

**Pull request merged**
